version: '3'

services:
  db:
    image: postgres:11
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_DB=${DB_NAME}
  backend:
    image: 'backend'
    depends_on:
      - cache
    restart: always
    volumes:
      - ../:/app
    ports:
      - '5000:5000'
    environment:
      - REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID}
      - REDDIT_CLIENT_SECRET=${REDDIT_CLIENT_SECRET}
      - REDDIT_USER_AGENT=${REDDIT_USER_AGENT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
  cache:
    image: 'redis:latest'
    restart: always
    ports:
      - '6379:6379'
