version: '3'

services:
  backend:
    image: 'backend'
    depends_on:
      - redis
    ports:
      - '5000:5000'
    environment:
      - REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID}
      - REDDIT_CLIENT_SECRET=${REDDIT_CLIENT_SECRET}
      - REDDIT_USER_AGENT=${REDDIT_USER_AGENT}
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
